# repository root netlify.toml
[build]
  base = "web/"
  publish = "web/dist/"
  command = "npm run build && npm run build.static"

[[redirects]]
  from = "/checklist/*"
  to = "/checklist/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false